apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: ai
data:
  librechat.yaml: |
    version: 1.1.5
    cache: true
    
    endpoints:
      custom:
        - name: "Ollama"
          apiKey: "ollama"
          baseURL: "http://ollama:11434/v1"
          models:
            default:
              - "qwen2.5:14b-instruct-q4_K_M"
            fetch: false
          titleConvo: true
          titleModel: "qwen2.5:14b-instruct-q4_K_M"
          summarize: false
          summaryModel: "qwen2.5:14b-instruct-q4_K_M"
          forcePrompt: false
          modelDisplayLabel: "Ollama"
